# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "nmL5ETRDtXy1bcmmkz9LCturNo4BaU9Z6ZjBkAO4rqFAnDLlYXHxoG6x2JeW2E9z2KPsR+4n80nOoQrbpkLyi5GduOr6If/mla0vcKyBCrXpZsePatQ1Ti3EeFp0wOZflmTf32S9QC2Qe9mi4a5uFRjL2J7Mv/PNmc1wOevKVpWZad6441TnvQH/rvBmowTd191ljtjEl705MRmAiRaDefCgkoJqT2uKg1TZSmIrk8xtuVHi0v+RHMRZV6jBYD9gXLcKTZnOFw+JQ37dzT8QJPolscifZfYQ2GjeLq6/8zMlAL18Bc3XbRShLgSS08YG6XPebNbBwY/FzzzzzvfBk0PFLTLqnn1o9KynPZefKO/RtFXr6ir8/qGFAdvW7r4AmrlmanKyCAXEpXMV4xRbg3knVDN8TwmzhxsjPetDnfYFslohf+etqmUOqFNmiNLmc/DDDee1TSZwZmWWG3xikZfcZ/iUAJJbxKR3+3YuRb77WxhndKwrEeWMFkqAj75CDzLmjRCoaxYLgnzlF5Q/k/Vm86TwMde/3Oxw8apmyX/triBd7cXWdiReJvHOmrC9HdZJQ+jqP4ywI8RZdrxtjEoccmmhK2elqr3HPhf9lj9smd74HcgBnlsD3l9JSAr5ONBJCqpUDRPUlqSN5laxkL9GoA9+owP9Am8tBeKq59Q="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
