travis:
  secure:
    BINSTAR_TOKEN: nmL5ETRDtXy1bcmmkz9LCturNo4BaU9Z6ZjBkAO4rqFAnDLlYXHxoG6x2JeW2E9z2KPsR+4n80nOoQrbpkLyi5GduOr6If/mla0vcKyBCrXpZsePatQ1Ti3EeFp0wOZflmTf32S9QC2Qe9mi4a5uFRjL2J7Mv/PNmc1wOevKVpWZad6441TnvQH/rvBmowTd191ljtjEl705MRmAiRaDefCgkoJqT2uKg1TZSmIrk8xtuVHi0v+RHMRZV6jBYD9gXLcKTZnOFw+JQ37dzT8QJPolscifZfYQ2GjeLq6/8zMlAL18Bc3XbRShLgSS08YG6XPebNbBwY/FzzzzzvfBk0PFLTLqnn1o9KynPZefKO/RtFXr6ir8/qGFAdvW7r4AmrlmanKyCAXEpXMV4xRbg3knVDN8TwmzhxsjPetDnfYFslohf+etqmUOqFNmiNLmc/DDDee1TSZwZmWWG3xikZfcZ/iUAJJbxKR3+3YuRb77WxhndKwrEeWMFkqAj75CDzLmjRCoaxYLgnzlF5Q/k/Vm86TwMde/3Oxw8apmyX/triBd7cXWdiReJvHOmrC9HdZJQ+jqP4ywI8RZdrxtjEoccmmhK2elqr3HPhf9lj9smd74HcgBnlsD3l9JSAr5ONBJCqpUDRPUlqSN5laxkL9GoA9+owP9Am8tBeKq59Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
