travis:
  secure:
    BINSTAR_TOKEN: iMiRNQa5L/f+VhX0UD8UknUUACDHlE7vi83Uhm8+6BqNZ+NSzD63z2sDBt8ac8HHSkCLkZD0EQhxvsPxFWUI0+sUj3QeNRTm/oVyFd5FRPnLqz66E4wNu7KrjJv0tfXeuS1gz3IA+0Wl4uGFaiHfF/eduVGGnCAms/aG0+u+uetBsKZf4iFUymFb1Pi5zyYuV4Y+2s4x3MvY4Ksr3DmGh61cNkMZpuzLhEiQYJt6+3YZKeU/o813Dv8ZyYGLy1WnQBfMyCCGKRnfWSc1WNp/xy6pBc/uAvliWLPcf62Qz+YDdeGIuiyN9HDm3NFDAmfzsrcyUnZwtG/J4x4MgfvRIMhF4fu3kw1ZYhoo6aSdBH6MKZriMkv/U/JQEJALSkDqQbYWMYFzQQxmwu0CwGSGNGKIOKA+PESi8LtLVkRF0V3/N/B5LCIK1PcQDtzKoIkFr63DY/cg49oPhvmd1D71WBbET1x9NpAghHcm+Gbh+N0gCFUtdt8Y0P6UCWahFQjzVoGvwmcdftao52Es7QR+WpBD86HjH0k4b7r3Bxya7Trut5e+8tn/1KulPYdqMEKWkHXeB+SywL7YRlnEXSVysC70FSx37IlUNrnMC2xOqCDR5J4vDxtgz8n0xGPqtonwcgIGiah2BI03wBv7CcDNp/fmLaJOJksdSPYZZUhwhTE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
